site_name: Guille Pistos
site_description: Donde publico mis "pistos"
site_url: https://fastapi.tiangolo.com/
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
# repo_name: tiangolo/fastapi
# repo_url: https://github.com/tiangolo/fastapi
edit_uri: ''
plugins:
- search
- markdownextradata:
    data: data
nav:
- Home: index.md
- Formacion:
    - Física:
        - Termodinámica: formacion/fisicas/termodinamica.md
    - Matematicas:
        - EDOs: formacion/matematicas/edos.md
        - PDEs: formacion/matematicas/pdes.md
        - Bayes: formacion/matematicas/bayes.md
    - Programacion:
        - Python:
            - Decorators: formacion/programacion/python/decorators.md
        - Docker: index.md
        - Kubernetes: index.md
        - AWS:
            - DynamoDB: formacion/programacion/aws/dynamodb.md
- Opinion:
    - Matematicas:
        - EDOs: formacion/matematicas/edos.md
        - PDEs: formacion/matematicas/pdes.md
- Languages:
    - en: /
    - es: /es/
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/eltbus/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/gsabreu1
  - icon: fontawesome/brands/linkedin
    link: www.linkedin.com/in/guille-sanchez-de-abreu
  - icon: fontawesome/solid/globe
    link: https://tiangolo.com
  alternate:
  - link: /
    name: en - English
  - link: /es/
    name: es - español
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
